name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2
    - run: flutter test
    - uses: GoogleCloudPlatform/lcov-coverage-badgev@v1.0.0
      file: ./coverage/lcov.info